- dmm-crm-plugin.php
- includes/classes/class-dmmcrm-location-meta.php
- includes/classes/class-dmmcrm-psalm-119.php
- includes/dmmcrm-admin-setup.php
- includes/dmmcrm-dashboard.php
- includes/dmmcrm-security-setup.php
Cleaned up various classes, added psalms class
> Cleaned up text, Add Psalms

- includes/dmmcrm-p2p-config.php
Corrected a broken ‘admin_column’ parameter with the p2p plugin. I
believe it is because of being a recursive post contact to contact.
> Corrected 'admin_column' parameter.

- includes/admin/config-admin.php
- includes/admin/config-settings.php
This will be useful for plugins to add their own settings to the DT settings area
Also fixed settings not saving
> rename hooks used to add settings to the DT settings pages

- includes/models/class-contact-post-type.php
This might become a select or something down the road. Or might transform into source_details.
> Add source field to contacts post type

- disciple-tools.php
- includes/admin/class-activator.php
- includes/models/class-contact-post-type.php
- includes/portal/class-portal-menu.php
There is one significant edit here on the post type for contacts. I adjusted the rewrite url to be contacts, because that is consistent with the post type name. Does this have any consequence to anything recently done with the Facebook Integration?
> Minor edits. One post type edit to the rewrite URL

- disciple-tools.php
- includes/admin/class-google-analytics-integration.php
- includes/plugins/google-analytics/README.md
- includes/plugins/google-analytics/class/Ga_Autoloader.php
- includes/plugins/google-analytics/class/Ga_Helper.php
- includes/plugins/google-analytics/class/Ga_Hook.php
- includes/plugins/google-analytics/class/Ga_Notice.php
- includes/plugins/google-analytics/class/Ga_Stats.php
- includes/plugins/google-analytics/class/Ga_View.php
- includes/plugins/google-analytics/class/controller/Ga_Admin_Controller.php
- includes/plugins/google-analytics/class/core/Ga_Controller_Core.php
- includes/plugins/google-analytics/class/core/Ga_View_Core.php
- includes/plugins/google-analytics/css/ga_additional.css
- includes/plugins/google-analytics/css/ga_modal.css
- includes/plugins/google-analytics/css/googleanalytics.css
- includes/plugins/google-analytics/disciple-tools-analytics.php
- includes/plugins/google-analytics/js/googleanalytics.js
- includes/plugins/google-analytics/js/googleanalytics_page.js
- includes/plugins/google-analytics/lib/Ga_Lib_Api_Client.php
- includes/plugins/google-analytics/lib/Ga_Lib_Api_Request.php
- includes/plugins/google-analytics/lib/Ga_Lib_Api_Response.php
- includes/plugins/google-analytics/lib/Ga_Lib_Google_Api_Client.php
- includes/plugins/google-analytics/overwrite/ga_overwrite.php
- includes/plugins/google-analytics/tools/Ga_Cache.php
- includes/plugins/google-analytics/view/ga_googleanalytics_loader.php
- includes/plugins/google-analytics/view/ga_notice.php
- includes/plugins/google-analytics/view/ga_oauth_notice.php
- includes/plugins/google-analytics/view/ga_wp_notice.php
- includes/plugins/google-analytics/view/page.php
@ChrisChasm I included the GA library in the plugins folder. What do you think?
> Include analytics

- disciple-tools.php
- includes/activity/class-integrations.php
- includes/activity/class-reports-api.php
- includes/activity/class-reports-cron.php
- includes/admin/class-facebook-integration.php
- js/disciple-tools-admin.js
> Facebook integration

- disciple-tools.php
- includes/admin/class-api-keys.php
- includes/admin/views/api-keys-view.php
Admin menu (under tools) for creating api keys.
> Api tokens

- includes/models/class-contact-post-type.php
@ChrisChasm These changes are needed in order to modify or set the contact details from the rest api. 
The type of a Primary Phone number will always be "primary". But each channel (Phone, Email...) has a label that, which can be the translation. Same with the types (primary, moblie...)
THis lets the db key (contact_phone_primary_*) always be the same and allows the rest api to work whatever the language.
> Contact details

- disciple-tools.php
Need to continue conversation from the Zume search
> Backed off the api which is redundant

- disciple-tools.php
> minor file additions

- .gitignore
- dt-core/config-p2p.php
- dt-groups/groups-post-type.php
Changed leadership tracking with members on the groups, removed the 4 fields meta box.
> Groups Tracking Changes

- dt-locations/admin-menu.php
- dt-locations/admin-tab-import.php
- dt-locations/admin-tab-stats.php
> Omega zone install

- dt-contacts/contacts-endpoints.php
> Contacts List: Show name for dispatch || user || group

- dt-contacts/contacts.php
- dt-core/posts.php
- dt-groups/groups-endpoints.php
- dt-groups/groups.php
Group Activity and comments
Using posts.php
> Group activity comments

- dt-contacts/contacts-endpoints.php
- dt-contacts/contacts-post-type.php
- dt-contacts/contacts-template.php
- dt-groups/groups-post-type.php
Remove the option to assign to 'Dispatch' and groups.
Fixes #138  and #137
> Posts can only be assigned to users

- dt-contacts/contacts.php
- dt-core/admin/tables/notifications-table.php
- dt-notifications/hooks/class-hook-comments.php
- dt-notifications/notifications-endpoints.php
- dt-notifications/notifications.php
> Notifications

- dt-core/admin/class-activator.php
- dt-core/admin/metaboxes/box-activity.php
- dt-core/admin/tables/notifications-table.php
- dt-notifications/README.md
- dt-notifications/hooks/class-hook-comments.php
- dt-notifications/hooks/class-hook-field-updates.php
- dt-notifications/notifications.php
Requires update working,
Upgrades to prevent XSS,
@mentions generates shares with the contact.
> Notifications: Requires Update

- dt-contacts/contacts.php
- dt-notifications/README.md
- dt-notifications/hooks/class-hook-field-updates.php
- dt-notifications/notifications.php
contact, address, and share notifications
> Notifications hooks

- dt-core/config-p2p.php
- dt-users/users-template.php
This included a patch for https://github.com/DiscipleTools/disciple-tools-theme/pull/54#issuecomment-332496906
> Site options

- dt-core/admin/class-activator.php
- dt-core/admin/config-site-defaults.php
- dt-core/admin/menu/tab-general.php
- dt-core/admin/menu/tabs-custom-lists.php
- dt-core/admin/user-groups/user-groups-taxonomies.php
- dt-core/core-functions.php
- dt-core/logging/class-reports-cron.php
- dt-core/posts.php
- dt-users/users-endpoints.php
- dt-users/users-template.php
- dt-users/users.php
These two functions support the edits to the template-settings.php
> Added Locations Listing, Added Team/Member Listing

- dt-core/admin/config-site-defaults.php
- dt-users/users-endpoints.php
- dt-users/users-template.php
- dt-users/users.php
template, js api, endpoints, controller, option checker/creator.
> Added user availability option

- dt-asset-mapping/asset-mapping-post-type.php
- phpcs.xml
I may be pushing more commits to this pull request later.
> Enable PHPCS and fix related errors

- dt-core/admin/menu/tab-setup-checklist.php
- dt-notifications/notifications-endpoints.php
- dt-notifications/notifications.php
working edits for the notifications page.
> Final notifications

- dt-notifications/hooks/class-hook-comments.php
https://github.com/DiscipleTools/disciple-tools/issues/190
> Fix for the @mention punctuation issue.

- dt-core/admin/config-dashboard.php
- dt-core/admin/enqueue-scripts.php
- dt-core/admin/js/dt-dashboard.js
- dt-metrics/class-counter.php
- dt-metrics/counters/counter-baptism.php
- dt-metrics/counters/counter-contacts.php
- dt-metrics/counters/counter-groups.php
- dt-metrics/metrics.php
- dt-notifications/hooks/class-hook-field-updates.php
Added all but prayer, social, and web counters for critical path
https://github.com/DiscipleTools/disciple-tools/issues/245
> Critical Path Metrics

- disciple-tools.php
- dt-core/logging/class-reports-api.php
- dt-core/migrations/0000-initial.php
- dt-metrics/README.md
- dt-metrics/class-counter.php
- dt-metrics/counters/counter-connected.php
- dt-metrics/counters/counter-contacts.php
- dt-metrics/counters/counter-generations-status.php
- dt-metrics/counters/counter-groups.php
- dt-metrics/counters/counter-outreach.php
- dt-metrics/counters/counter-prayer.php
Fix to cron report variable
Added a couple counter classes
Added prayer network statistic
Added two columns to reports
> Preparing Reports

- dt-core/admin/metaboxes/box-map.php
- dt-core/logging/hooks/class-hook-posts.php
Fixes #265 
@ChrisChasm, It looks like you only tested the import location strategy. On create new location the map was trying to load without any location.
> Location fixes

- dt-core/admin/class-roles.php
- dt-locations/admin-menu.php
- dt-people-groups/admin-menu.php
The logic with the dt-admin is to allow a leader to be able to sign in
and add users.
> Added dt-admin role
